/* Orbis – englische Inhalte. Die Spiellogik arbeitet mit den deutschen Begriffen,
   angezeigt wird je nach Sprache die Übersetzung. Die Arrays unten sind
   nach Index mit den Listen in data.js verknüpft – Reihenfolge nicht ändern. */
const TERM_EN = {
  // Länder
  "Deutschland":"Germany","Österreich":"Austria","Schweiz":"Switzerland","Frankreich":"France","Italien":"Italy","Spanien":"Spain",
  "Vereinigtes Königreich":"United Kingdom","Irland":"Ireland","Niederlande":"Netherlands","Belgien":"Belgium","Luxemburg":"Luxembourg",
  "Dänemark":"Denmark","Norwegen":"Norway","Schweden":"Sweden","Finnland":"Finland","Island":"Iceland","Polen":"Poland","Tschechien":"Czechia",
  "Slowakei":"Slovakia","Ungarn":"Hungary","Slowenien":"Slovenia","Kroatien":"Croatia","Bosnien und Herzegowina":"Bosnia and Herzegovina",
  "Serbien":"Serbia","Albanien":"Albania","Nordmazedonien":"North Macedonia","Griechenland":"Greece","Bulgarien":"Bulgaria","Rumänien":"Romania",
  "Moldau":"Moldova","Litauen":"Lithuania","Lettland":"Latvia","Estland":"Estonia","Russland":"Russia","Türkei":"Turkey","Zypern":"Cyprus",
  "Südkorea":"South Korea","Nordkorea":"North Korea","Indien":"India","Bangladesch":"Bangladesh","Indonesien":"Indonesia","Philippinen":"Philippines",
  "Mongolei":"Mongolia","Kasachstan":"Kazakhstan","Usbekistan":"Uzbekistan","Saudi-Arabien":"Saudi Arabia","Ägypten":"Egypt","Kenia":"Kenya",
  "Äthiopien":"Ethiopia","Marokko":"Morocco","Algerien":"Algeria","Tunesien":"Tunisia","Libyen":"Libya","Tansania":"Tanzania","DR Kongo":"DR Congo",
  "Tschad":"Chad","Madagaskar":"Madagascar","Südafrika":"South Africa","Kanada":"Canada","Mexiko":"Mexico","Kuba":"Cuba","Jamaika":"Jamaica",
  "Brasilien":"Brazil","Argentinien":"Argentina","Kolumbien":"Colombia","Bolivien":"Bolivia","Australien":"Australia","Neuseeland":"New Zealand",
  "Papua-Neuguinea":"Papua New Guinea","Aserbaidschan":"Azerbaijan","Irak":"Iraq","Georgien":"Georgia","Libanon":"Lebanon","Kirgisistan":"Kyrgyzstan",
  "Vatikanstadt":"Vatican City","Mosambik":"Mozambique","Jordanien":"Jordan","Dominikanische Republik":"Dominican Republic","Bahamas":"The Bahamas",
  "Trinidad und Tobago":"Trinidad and Tobago",
  // Hauptstädte und Städte
  "Wien":"Vienna","Rom":"Rome","Lissabon":"Lisbon","Brüssel":"Brussels","Kopenhagen":"Copenhagen","Warschau":"Warsaw","Prag":"Prague",
  "Belgrad":"Belgrade","Athen":"Athens","Bukarest":"Bucharest","Kiew":"Kyiv","Moskau":"Moscow","Nikosia":"Nicosia","Peking":"Beijing","Tokio":"Tokyo",
  "Neu-Delhi":"New Delhi","Pjöngjang":"Pyongyang","Taschkent":"Tashkent","Teheran":"Tehran","Riad":"Riyadh","Kairo":"Cairo","Algier":"Algiers",
  "Tripolis":"Tripoli","Addis Abeba":"Addis Ababa","Mexiko-Stadt":"Mexico City","Havanna":"Havana","Panama-Stadt":"Panama City",
  "Guatemala-Stadt":"Guatemala City","Genf":"Geneva","Zürich":"Zurich","Daressalam":"Dar es Salaam","Sansibar-Stadt":"Zanzibar City",
  "Marrakesch":"Marrakesh","Fès":"Fez","Schymkent":"Shymkent","Ho-Chi-Minh-Stadt":"Ho Chi Minh City","Karatschi":"Karachi","Hongkong":"Hong Kong",
  "Dschidda":"Jeddah","Mekka":"Mecca","Gizeh":"Giza","Mailand":"Milan","Neapel":"Naples","Florenz":"Florence","Sevilla":"Seville","München":"Munich",
  "Venedig":"Venice","Windsor (Kanada)":"Windsor (Canada)","Panama-Stadt (Pazifik)":"Panama City (Pacific)","Colón (Atlantik)":"Colón (Atlantic)",
  "Kapstadt":"Cape Town","Singapur":"Singapore",
  // Antworten aus Wissensfragen
  "Donau":"Danube","Nil":"Nile","Rhein":"Rhine","Amazonas":"Amazon","Kap Agulhas":"Cape Agulhas","Kap der Guten Hoffnung":"Cape of Good Hope",
  "Kap Hoorn":"Cape Horn","Kap Verde":"Cape Verde","rund 4 km":"about 4 km","rund 80 km":"about 80 km","rund 400 km":"about 400 km",
  "rund 1.200 km":"about 1,200 km","Afrika":"Africa","Asien":"Asia","Europa":"Europe","Südamerika":"South America","Wolga":"Volga","Dnepr":"Dnieper",
  "Kaspisches Meer":"Caspian Sea","Oberer See":"Lake Superior","Baikalsee":"Lake Baikal","Victoriasee":"Lake Victoria",
  "Tanganjikasee":"Lake Tanganyika","Titicacasee":"Lake Titicaca"
};

const COMPASS_EN = [
  "Europe lies much further north than it feels – the Gulf Stream keeps it warm.",
  "Madrid and Beijing sit on almost the same latitude – Madrid just slightly further north.",
  "London lies further north than Calgary in the Canadian prairies.",
  "Paris lies a good 3 degrees of latitude further north than Montreal.",
  "Seattle, the rainy city in the US Northwest, lies further south than Paris.",
  "The other way round: Chicago is actually a bit further north than Barcelona.",
  "Anchorage in Alaska lies further north than Oslo.",
  "Venice lies almost 2 degrees further north than Toronto.",
  "Athens lies further north than Tokyo.",
  "Munich lies just slightly further south than Vienna.",
  "From Detroit you drive south to reach Canada – Windsor lies further south.",
  "Miami lies much further south than Cairo.",
  "California's coast bends east – Reno, Nevada, lies further west than Los Angeles.",
  "All of South America lies further east than you'd think – Miami is further west than Santiago de Chile.",
  "Even Lima on the Pacific coast lies further east than Miami.",
  "Vienna lies further east than Prague – even though Prague is often called “Eastern Europe”.",
  "Helsinki lies further east than Athens.",
  "Lisbon lies further west than Dublin.",
  "Edinburgh really is slightly further north than Moscow.",
  "Berlin lies about one degree further north than London.",
  "Barcelona lies further south than Rome.",
  "Venice lies further west than Salzburg.",
  "Great Britain is tilted – Edinburgh lies further west than Bristol.",
  "Naples lies almost one degree further north than Beijing.",
  "The Panama Canal runs diagonally: its Pacific end lies further east than its Atlantic end.",
  "Kyiv lies further east than Istanbul."
];

const HIGHER_EN = [
  "Colombia has more people than vast Canada.",
  "Ghana has more people than all of Australia.",
  "Bangladesh – smaller than Greece and Austria combined – has more people than Russia.",
  "Ethiopia has about one and a half times as many people as Germany.",
  "DR Congo has far more people than Italy.",
  "Kenya has more people than Spain.",
  "Mexico now has more people than Japan.",
  "Madagascar is bigger than mainland France.",
  "New Zealand is bigger than the United Kingdom.",
  "Japan is bigger than Germany.",
  "Kenya is bigger than Spain.",
  "Kazakhstan is even bigger than Algeria, Africa's largest country.",
  "Libya is bigger than Mongolia.",
  "Italy is a little bigger than New Zealand.",
  "Brazil is bigger than Australia.",
  "Argentina is more than twice the size of Peru.",
  "Pakistan has more people than Brazil.",
  "Egypt has far more people than Germany.",
  "Vietnam has more people than Germany.",
  "Saudi Arabia is bigger than Mexico.",
  "Poland is a little bigger than Italy.",
  "The United Kingdom is only just bigger than Romania."
];

const OUTLIERS_EN = [
  ["Which country does NOT border Germany?","Austria and Switzerland lie between Germany and Italy."],
  ["Which country does NOT border Austria?","Croatia is close, but Slovenia and Hungary lie in between."],
  ["Which country does NOT border Russia?","Russia even borders North Korea – but not Romania."],
  ["Which country does NOT border Brazil?","Brazil borders every South American country except Chile and Ecuador."],
  ["Which country does NOT border China?","China has 14 neighbors, but Thailand isn't one – Laos and Myanmar lie in between."],
  ["Which country does NOT border Spain?","Spain borders Morocco via Ceuta and Melilla, and the United Kingdom via Gibraltar."],
  ["Which country does NOT border France?","Through French Guiana, France borders Brazil – but not Portugal."],
  ["Which country does NOT border Switzerland?","Slovenia lies beyond Austria and Italy."],
  ["Which country does NOT border Hungary?","Hungary has seven neighbors – Czechia isn't one of them."],
  ["Which country does NOT border Poland?","Poland borders Russia via the Kaliningrad exclave, but not Latvia."],
  ["Which country does NOT border Italy?","The Adriatic separates Italy and Croatia – on land, Slovenia lies in between."],
  ["Which country does NOT border Czechia?","Slovakia lies between Czechia and Hungary."],
  ["Which country does NOT border Argentina?","Bolivia and Chile separate Peru from Argentina."],
  ["Which country does NOT border India?","Myanmar lies between India and Thailand."],
  ["Which country does NOT border Croatia?","Austria is close, but Slovenia and Hungary lie in between."],
  ["Which country does NOT border Turkey?","Via the Nakhchivan exclave, Turkey even borders Azerbaijan – but not Lebanon."]
];

const TRIVIA_EN = [
  ["Which country has the most time zones?","Thanks to its overseas territories, France spans 12 time zones – more than any other country."],
  ["Which river flows through the most countries?","The Danube flows through 10 countries – from Germany to Ukraine."],
  ["Which country is surrounded only by landlocked countries – making it doubly landlocked?","There are only two doubly landlocked countries in the world: Liechtenstein and Uzbekistan."],
  ["Which country has shared a land border with Canada since 2022?","Hans Island between Greenland and Canada was split in 2022 – since then Canada and Denmark share a land border."],
  ["What is the southernmost point of Africa?","Not the famous Cape of Good Hope, but Cape Agulhas, about 150 km to the southeast."],
  ["Which seat of government lies the highest?","La Paz in Bolivia sits at around 3,600 meters."],
  ["Which country has the longest coastline in the world?","Thanks to its many Arctic islands, Canada's coastline is by far the longest."],
  ["Which country has more pyramids than Egypt?","Sudan has over 200 Nubian pyramids – more than Egypt."],
  ["Which country is crossed by both the Equator and the Tropic of Capricorn?","The Equator runs through northern Brazil, the Tropic of Capricorn through the state of São Paulo."],
  ["How close do Russia and the USA get at their nearest point?","Only about 4 kilometers separate the Diomede Islands in the Bering Strait."],
  ["Which is the only national flag that isn't rectangular?","Nepal's flag is made of two stacked triangles. Switzerland and the Vatican have square flags."],
  ["Which continent has the most countries?","Africa has 54 internationally recognized states."],
  ["What is the smallest country in the world?","Vatican City covers only about 0.44 km²."],
  ["How many countries border Austria?","Germany, Czechia, Slovakia, Hungary, Slovenia, Italy, Switzerland and Liechtenstein."],
  ["What is the longest river in Europe?","The Volga is about 3,500 km long – much longer than the Danube."],
  ["What is the largest lake on Earth?","Despite its name, the Caspian Sea is a lake – and by far the largest."],
  ["What is the deepest lake on Earth?","Lake Baikal in Siberia is over 1,600 meters deep."],
  ["Which country has the largest population in Africa?","Nigeria has more than 200 million people."],
  ["Which of these capitals lies furthest north?","Reykjavík is the northernmost capital of a sovereign state."],
  ["How many time zones does Russia span?","From Kaliningrad to Kamchatka, it covers 11 time zones."],
  ["Which major city lies on two continents?","The Bosporus divides Istanbul into a European and an Asian side."],
  ["Which country has the most islands?","Sweden counts more than 260,000 islands – most of them tiny."]
];

const DETECTIVE_EN = [
  ["Traffic drives on the left here.","The country borders exactly one other country.","The flag is green, white and orange."],
  ["The country is over 4,000 km long but only about 180 km wide on average.","One of the driest deserts on Earth is here.","Easter Island belongs to it."],
  ["A landlocked country with exactly two neighbors.","No sovereign state is more sparsely populated.","Its capital is considered the coldest capital in the world."],
  ["A landlocked country in South America.","Despite having no coast, it maintains a navy.","The largest salt flat on Earth is here."],
  ["The country consists of more than 17,000 islands.","It is the most populous Muslim-majority country.","The flag is red and white – almost identical to Monaco's."],
  ["The country has the longest coastline in the world.","It has more lakes than any other country.","Since 2022 it has shared a land border with Denmark."],
  ["The country has just under 50 km of coastline.","It borders Italy, Austria, Hungary and Croatia.","Its capital is Ljubljana."],
  ["A landlocked country with exactly two neighbors.","Eight of the fourteen 8,000-meter peaks stand fully or partly here.","Its flag is the only one that isn't rectangular."],
  ["The country sits on the Mid-Atlantic Ridge.","It has no army of its own.","Its capital is the northernmost of any sovereign state."],
  ["It is the largest landlocked country in the world.","Yuri Gagarin launched into space from here.","Its capital is Astana."],
  ["There are four national languages here.","The country borders Liechtenstein.","The flag is square."],
  ["An EU country that drives on the left.","It is the smallest EU member by area.","Its capital is Valletta."],
  ["Apart from a brief occupation, the country was never colonized.","Its own calendar runs about 7 to 8 years behind ours.","Since 1993 it has had no access to the sea."],
  ["Far more sheep than people live here.","Its capital is the southernmost of any sovereign state.","Women could vote nationally here as early as 1893."],
  ["The country borders ten states.","Both the Equator and the Tropic of Capricorn cross it.","Its official language is Portuguese."],
  ["Traffic drives on the left here.","The country consists of more than 14,000 islands.","Its highest mountain is a volcano that last erupted in 1707."],
  ["The country borders exactly one other country.","The westernmost point of mainland Europe is here.","The Azores and Madeira belong to it."],
  ["The country lies on two continents.","Almost the entire population lives along a single river.","The Suez Canal is here."],
  ["Traffic drives on the left here.","The capital was purpose-built because two big cities couldn't agree.","Uluru is here."],
  ["The country completely surrounds two other states.","Europe's highest active volcano stands here.","Its capital is Rome."],
  ["In summer, the sun doesn't set for weeks in some places here.","Svalbard belongs to it.","Its capital is Oslo."],
  ["The Amazon has its source here.","Half of Lake Titicaca lies in this country.","Machu Picchu is here."],
  ["Traffic drives on the left here.","The Ganges flows through this country.","No country has more people."],
  ["It is the largest island in the Caribbean.","The USA is only about 150 km away.","Its capital is Havana."],
  ["It is the fourth-largest island on Earth.","About 90% of its plant and animal species are found nowhere else.","Lemurs live here."],
  ["About a quarter of the country lies below sea level.","There are more bicycles here than people.","The seat of government is not the capital."]
];
